import { MONGODB_URL } from "./dbConfig";
import { ACCESS_TOKEN_SECRET, REFRESH_TOKEN_SECRET } from "./tokens";
import { 
    ADMIN_GOOGLE_EMAIL,
    ADMIN_GOOGLE_PASSWORD,
    OAUTH_CLIENT_ID,
    OAUTH_CLIENT_SECRET,
    OAUTH_REFRESH_TOKEN 
} from "./userConfig";

export {
    MONGODB_URL,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    ADMIN_GOOGLE_EMAIL,
    ADMIN_GOOGLE_PASSWORD,
    OAUTH_CLIENT_ID,
    OAUTH_CLIENT_SECRET,
    OAUTH_REFRESH_TOKEN 
}